version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: sae203_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sae203Base
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    image: php:8.2-apache
    container_name: sae203_php
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    container_name: sae203_pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
